### ISSUE TITLE
file not available on dataverse

### ISSUE THREAD

**Issue by renskegelderloos** [JuliaClimate/GlobalOceanNotebooks#27]
In notebooks 06 and 07, velocity fields are loaded using dataverse. However, the files no longer seem to be there, or perhaps the path has changed:

IOError: could not spawn `wget --content-disposition https://dataverse.harvard.edu/api/access/datafile/2845329`: no such file or directory (ENOENT)

**Comment by gaelforget** [comment]
Hi @renskegelderloos 

Sorry for that. Not sure what happened but my guess is that the issue was due to the notebooks being out of date vs packages where I implemented breaking changes since then. 

Should work now based on yesterday's updates -- they did both on my laptop and in cloud using https://mybinder.org/v2/gh/JuliaClimate/GlobalOceanNotebooks/master using Julia v1.5

Could you give this another try? Can we close the issue?

**Comment by renskegelderloos** [comment]
Yes, all good. Thanks!
